#!/bin/sh
#
# @name UUV
#
# @type Boat
# @class Boat
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer
#

sh /etc/init.d/rc.uuv2_defaults

if [ $AUTOCNF = yes ]
then
	# disable circuit breaker for airspeed sensor
	param set CBRK_AIRSPD_CHK 162128
	#param set CBRK_GPSFAIL 240024
        param set PWM_MAX 2000
        param set PWM_MIN 1000
fi

set PWM_RATE 50
set MAV_TYPE 12

set MIXER uuv2
